version: "3.7"

services:

  portainer:
    image: portainer/portainer-ce:linux-amd64-2.19.0-alpine
    ports:
      - 8000:8000 
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /portainer_data:/data
    restart: always
      
    
